name: First GitHub Action

on:
  push:
    branches:
      - main
    paths-ignore:
      - src/**

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate output file
        run: |
          echo "Hello, GitHub Actions!" > output1.txt
          date >> output1.txt
          uname -a >> output1.txt
          pwd >> output1.txt
          whoami >> output1.txt
          #env | sort >> output1.txt

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-output
          path: output1.txt
